<div class="page-margin">
	<div class="container">
		<h2 class="tag_page_title m5"><?php echo $wo['lang']['explore'] ?></h2>

		<div class="profile-lists">
			<div id="photos-list" class="user_media_list_section insta">
			 <?php foreach ($wo['explore_posts'] as $wo['story']) { 
				echo Wo_LoadPage('mode_instagram/explore/list');
			 } ?>
			</div>
			<?php if (count($wo['explore_posts']) > 0) { ?>
			<?php }else{
				echo Wo_LoadPage('mode_instagram/explore/no-posts');
			} ?>
		</div>
	</div>
</div>

<script type="text/javascript">
scrolled = 0;
$(window).scroll(function () {
	var nearToBottomm = 300;
	if($('.user_media_list_section').length > 0) {
		if ($(window).scrollTop() + $(window).height() > $(document).height() - nearToBottomm) {
			if (scrolled == 0) {
				scrolled = 1;
				Wo_LoadExplorePosts();
			}
		}
	}
});

	function Wo_LoadExplorePosts() {
		var after_post_id = $('div.photo-data:last').attr('data-post-id');
		$.post(Wo_Ajax_Requests_File() + '?f=explore&s=load_more_posts&mode_type=instagram', {
		    after_post_id: after_post_id,
		}, function (data) {
			if (data.status == 200) {
				if (data.html && data.html != '') {
					scrolled = 0;
					$('.user_media_list_section').append(data.html);
				}
				else{
					//$('.load-more-explore').slideUp();
				}
			}
			else{
				//$('.load-more-explore').slideUp();
			}
		});
	}
</script>