<?php 
$ramza_theme_settings = array();
if (mysqli_query($wo['sqlConnect'], "DESCRIBE `" . T_THEME_SETTINGS . "`" )) {
	$settings = $db->get(T_THEME_SETTINGS);
	foreach ($settings as $key => $value) {
		$ramza_theme_settings[$value->name] = $value->value;
	}
}
?>

<?php if (!empty($ramza_theme_settings) && $ramza_theme_settings['tag_header_layout'] == 1) { ?>
	<?php echo Wo_LoadPage('header/header-top'); ?>
<?php } else { ?>
	<?php echo Wo_LoadPage('header/header-side'); ?>
<?php } ?>