<div class="wo_ad_header_format list-group-jobs sidebar-ad-wrapper-jobs pointer rads-<?php echo $wo['sidebar-ad']['bidding']; ?>" id="<?php echo $wo['sidebar-ad']['id']; ?>">
    <div class="sidebar-ad-header-jobs sidebar-title-back-jobs sponsored"><?php echo $wo['lang']['sponsored'] ?></div>
    <div class="sidebar-ad-body imgs">
        <?php echo Wo_RenderAdMedia($wo['sidebar-ad']['ad_media'], 'Picture'); ?>
    </div>
    <div class="sidebar-ad-footer-jobs details">
        <p class="ad-title-jobs">
            <?php echo $wo['sidebar-ad']['headline']; ?>
        </p>
        <p class="small ad-descrition-jobs ">
            <?php echo $wo['sidebar-ad']['description']; ?>
        </p>
        <time>
            <a href="<?php  echo $wo['sidebar-ad']['url'];?>" class="main-jobs" target="_blank">
                <?php echo Wo_UrlDomain($wo['sidebar-ad']['url']); ?>
            </a>
        </time>
    </div>
</div>
