<div class="page-margin wo_user_profile tag_directory">
	<div class="container">
		<h2 class="tag_page_title m5">{{LANG welcome_discover}} {{LANG posts}}</h2>
		<div class="page-margin">
			<div class="post_prnt">
				{{sidebar}}
				<div class="row">
					<div class="col-lg-2"></div>
					<div class="col-lg-8">
						<div class="posts_load">
							{{html}}
						</div>
						{{pagination}}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>