<?php
$not_found = '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15.5,12C18,12 20,14 20,16.5C20,17.38 19.75,18.21 19.31,18.9L22.39,22L21,23.39L17.88,20.32C17.19,20.75 16.37,21 15.5,21C13,21 11,19 11,16.5C11,14 13,12 15.5,12M15.5,14A2.5,2.5 0 0,0 13,16.5A2.5,2.5 0 0,0 15.5,19A2.5,2.5 0 0,0 18,16.5A2.5,2.5 0 0,0 15.5,14M7,15V17H9C9.14,18.55 9.8,19.94 10.81,21H5C3.89,21 3,20.1 3,19V5C3,3.89 3.89,3 5,3H19A2,2 0 0,1 21,5V13.03C19.85,11.21 17.82,10 15.5,10C14.23,10 13.04,10.37 12.04,11H7V13H10C9.64,13.6 9.34,14.28 9.17,15H7M17,9V7H7V9H17Z" /></svg> ' . $wo["lang"]["no_result"] . '</div>';
$type_to_find = '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M9.62,12L12,5.67L14.37,12M11,3L5.5,17H7.75L8.87,14H15.12L16.25,17H18.5L13,3H11Z" /></svg> ' . $wo["lang"]["what_are_looking_for"] . '</div>';

$page = isset($_GET['page-id']) ? $_GET['page-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? Wo_Secure($_GET['query']) : '';
$db->pageLimit = 20;
$link = '';
$movies = $db->objectbuilder()->orderBy('id', 'DESC')->paginate(T_MOVIES, $page);


?>
<div class="page-margin wo_user_profile tag_directory">
	<div class="container">
		<h2 class="tag_page_title m5"><?php echo $wo['lang']['welcome_discover'] ?> <?php echo $wo['lang']['movies'] ?></h2>
		<div class="page-margin">
			<div class="movie_prnt">
				<?php echo Wo_LoadPage("directory/left-sidebar"); ?>

				<div class="row">
					<?php if (count($movies) > 0): ?>
						<?php foreach ($movies as $wo['film']): ?>
							<?php
							$wo['film'] = (array) $wo['film'];
							if (!empty($wo['film']['cover'])) {
								$wo['film']['cover'] = Wo_GetMedia($wo['film']['cover']);
							}
							$wo['film']['url'] = Wo_SeoLink("index.php?link1=watch-film&film-id=" . $wo['film']['id']) . '_' . Wo_SlugPost($wo['film']['name']);
							echo Wo_LoadPage("movies/includes/films-list"); ?>
						<?php endforeach ?>
					<?php else: ?>
						<?php echo '<div class="col-md-12"><div class="wow_content"><div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M18,9H16V7H18M18,13H16V11H18M18,17H16V15H18M8,9H6V7H8M8,13H6V11H8M8,17H6V15H8M18,3V5H16V3H8V5H6V3H4V21H6V19H8V21H16V19H18V21H20V3H18Z" /></svg>'. $wo['lang']['no_movies_found'] .' </div></div></div>';?>
					<?php endif; ?>
				</div>

				<?php if (!empty($movies)) { ?>
					<div class="valign wo-admincp-feturepager">
						<div><?php echo "Showing $page out of " . $db->totalPages; ?></div>
						<div>
							<nav>
								<ul class="pagination">
									<li>
										<a href="<?php echo Wo_Link('directory/movies?page-id=1') . $link; ?>" data-ajax="?link1=directory-movies&page-id=1<?php echo($link); ?>" title='First Page'>
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M11 7l-5 5l5 5"></path><path d="M17 7l-5 5l5 5"></path></svg>
										</a>
									</li>
									<?php if ($page > 1) { ?>
										<li>
											<a href="<?php echo Wo_Link('directory/movies?page-id=' . ($page - 1)) . $link; ?>" data-ajax="?link1=directory-movies&page-id=<?php echo ($page - 1) . $link; ?>" title='Previous Page'>
												<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M15 6l-6 6l6 6"></path></svg>
											</a>
										</li>
									<?php } ?>

									<?php
									$nums = 0;
									$nums_pages = ($page > 4) ? ($page - 4) : $page;

									for ($i = $nums_pages; $i <= $db->totalPages; $i++) {
										if ($nums < 20) {
											?>
											<li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
												<a href="<?php echo Wo_Link('directory/movies?page-id=' . ($i)) . $link; ?>" data-ajax="?link1=directory-movies&page-id=<?php echo ($i) . $link; ?>">
													<?php echo $i ?>
												</a>
											</li>

										<?php }
										$nums++;
									} ?>

									<?php if ($db->totalPages > $page) { ?>
										<li>
											<a href="<?php echo Wo_Link('directory/movies?page-id=' . ($page + 1)) . $link; ?>" data-ajax="?link1=directory-movies&page-id=<?php echo ($page + 1) . $link; ?>" title="Next Page">
												<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M9 6l6 6l-6 6"></path></svg>
											</a>
										</li>
									<?php } ?>
									<li>
										<a href="<?php echo Wo_Link('directory/movies?page-id=' . ($db->totalPages)) . $link; ?>" data-ajax="?link1=directory-movies&page-id=<?php echo($db->totalPages) ?><?php echo($link); ?>" title='Last Page'>
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M7 7l5 5l-5 5"></path><path d="M13 7l5 5l-5 5"></path></svg>
										</a>
									</li>
								</ul>
							</nav>
						</div>
					</div>
				<?php } ?>
			</div>
		</div>
	</div>
</div>