<div class="container-fluid">
    <div>
        <h3>Changelog</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Changelog</li>
            </ol>
        </nav>
    </div>

    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.0 <small>Initial release</small></h6>
                    <ul>
                        <li>Initial Ramza release.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
