<?php
	if (!empty($wo['story']['product_id']) && !empty($wo['story']['product']) && !empty($wo['story']['product']['images'])) {
		if ($wo['page']  == 'story') { ?>
			<style>.col-lg-7.middlecol {-ms-flex: 0 0 100%;flex: 0 0 100%;max-width: 100%;}.col-lg-3.sidebar.rightcol {display:none;}</style>
		<?php }
		$symbol = (!empty($wo['currencies'][$wo['story']['product']['currency']]['symbol'])) ? $wo['currencies'][$wo['story']['product']['currency']]['symbol'] : $wo['config']['classified_currency_s'];
		$text = (!empty($wo['currencies'][$wo['story']['product']['currency']]['text'])) ? $wo['currencies'][$wo['story']['product']['currency']]['text'] : $wo['config']['classified_currency'];
		$status = '<span class="">' . $wo['lang']['currently_unavailable'] . '</span>';
		if ($wo['story']['product']['units'] > 0) {
			$status = ($wo['story']['product']['status'] == 0) ? '' . $wo['lang']['in_stock'] . '' : '<span class="product-status-sold">' . $wo['lang']['sold'] . '</span>';
		}
		$type = ($wo['story']['product']['type'] == 0) ? '<span class="product-description">' . $wo['lang']['new'] . '</span>' : '<span class="product-description">' . $wo['lang']['used'] . '</span>';
		
		echo '<div class="valign tag_post_prods">';
		
		echo '<div class="prod_full_size_slide">';
		echo '<div id="tpc_' . $wo['story']['product_id'] . '" class="carousel slide" data-ride="carousel">';
		echo '<div class="carousel-inner">';
		foreach ($wo['story']['product']['images'] as $photo) {
			echo '<div class="carousel-item tag_post_prods_slide">';
			echo '<div class="tag_lbox_blur_img">';
			echo '<div class="tag_lbox_blur_img_innr">';
			echo "<img src='" . ($photo['image_org']) ."'>";
			echo '</div>';
			echo '</div>';
			echo '<div class="tag_post_prods_thumb">';
			echo "<img src='" . ($photo['image_org']) ."' class='pointer' onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"product\");'>";
			echo '</div>';
			echo '</div>';
		}
		echo '</div>';
		if (count($wo['story']['product']['images']) > 1) {
			echo '<a class="carousel-control-prev carousel-control" href="#tpc_' . $wo['story']['product_id'] . '" role="button" data-slide="prev">';
			echo '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M10.828 12l4.95 4.95-1.414 1.414L8 12l6.364-6.364 1.414 1.414z"></path></svg>';
			echo '</a>';
			echo '<a class="carousel-control-next carousel-control" href="#tpc_' . $wo['story']['product_id'] . '" role="button" data-slide="next">';
			echo '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M13.172 12l-4.95-4.95 1.414-1.414L16 12l-6.364 6.364-1.414-1.414z"></path></svg>';
			echo '</a>';
		}
		echo '</div>';
		echo '</div>';
		
		echo '<div class="full_width wow_post_prod">';
		echo '<h4 class="wow_post_prod_name">' . $wo['story']['product']['name'] . '</h4>';
		echo '<p class="wow_post_prod_price">' . $symbol . $wo['story']['product']['price_format'] . ' (' . $text . ')</p>';
		?>
			<?php
				$stars = '0';
				if (!empty($wo['story']['product']['rating']) && is_numeric($wo['story']['product']['rating'])) {
					$stars = $wo['story']['product']['rating'];
				}
			?>
			<?php if ($wo['config']['store_system'] == 'on') { ?>
				<div class="pr_stars" data-stars="<?php echo $stars; ?>">
					<svg class="star rating" viewBox="0 0 24 24" data-rating="1"><path d="M6.516,14.323l-1.49,6.452c-0.092,0.399,0.068,0.814,0.406,1.047C5.603,21.94,5.801,22,6,22 c0.193,0,0.387-0.056,0.555-0.168L12,18.202l5.445,3.63c0.348,0.232,0.805,0.223,1.145-0.024c0.338-0.247,0.487-0.68,0.372-1.082 l-1.829-6.4l4.536-4.082c0.297-0.268,0.406-0.686,0.278-1.064c-0.129-0.378-0.47-0.644-0.868-0.676L15.378,8.05l-2.467-5.461 C12.75,2.23,12.393,2,12,2s-0.75,0.23-0.911,0.589L8.622,8.05L2.921,8.503C2.529,8.534,2.192,8.791,2.06,9.16 c-0.134,0.369-0.038,0.782,0.242,1.056L6.516,14.323z"></path></svg>
					<svg class="star rating" viewBox="0 0 24 24" data-rating="2"><path d="M6.516,14.323l-1.49,6.452c-0.092,0.399,0.068,0.814,0.406,1.047C5.603,21.94,5.801,22,6,22 c0.193,0,0.387-0.056,0.555-0.168L12,18.202l5.445,3.63c0.348,0.232,0.805,0.223,1.145-0.024c0.338-0.247,0.487-0.68,0.372-1.082 l-1.829-6.4l4.536-4.082c0.297-0.268,0.406-0.686,0.278-1.064c-0.129-0.378-0.47-0.644-0.868-0.676L15.378,8.05l-2.467-5.461 C12.75,2.23,12.393,2,12,2s-0.75,0.23-0.911,0.589L8.622,8.05L2.921,8.503C2.529,8.534,2.192,8.791,2.06,9.16 c-0.134,0.369-0.038,0.782,0.242,1.056L6.516,14.323z"></path></svg>
					<svg class="star rating" viewBox="0 0 24 24" data-rating="3"><path d="M6.516,14.323l-1.49,6.452c-0.092,0.399,0.068,0.814,0.406,1.047C5.603,21.94,5.801,22,6,22 c0.193,0,0.387-0.056,0.555-0.168L12,18.202l5.445,3.63c0.348,0.232,0.805,0.223,1.145-0.024c0.338-0.247,0.487-0.68,0.372-1.082 l-1.829-6.4l4.536-4.082c0.297-0.268,0.406-0.686,0.278-1.064c-0.129-0.378-0.47-0.644-0.868-0.676L15.378,8.05l-2.467-5.461 C12.75,2.23,12.393,2,12,2s-0.75,0.23-0.911,0.589L8.622,8.05L2.921,8.503C2.529,8.534,2.192,8.791,2.06,9.16 c-0.134,0.369-0.038,0.782,0.242,1.056L6.516,14.323z"></path></svg>
					<svg class="star rating" viewBox="0 0 24 24" data-rating="4"><path d="M6.516,14.323l-1.49,6.452c-0.092,0.399,0.068,0.814,0.406,1.047C5.603,21.94,5.801,22,6,22 c0.193,0,0.387-0.056,0.555-0.168L12,18.202l5.445,3.63c0.348,0.232,0.805,0.223,1.145-0.024c0.338-0.247,0.487-0.68,0.372-1.082 l-1.829-6.4l4.536-4.082c0.297-0.268,0.406-0.686,0.278-1.064c-0.129-0.378-0.47-0.644-0.868-0.676L15.378,8.05l-2.467-5.461 C12.75,2.23,12.393,2,12,2s-0.75,0.23-0.911,0.589L8.622,8.05L2.921,8.503C2.529,8.534,2.192,8.791,2.06,9.16 c-0.134,0.369-0.038,0.782,0.242,1.056L6.516,14.323z"></path></svg>
					<svg class="star rating" viewBox="0 0 24 24" data-rating="5"><path d="M6.516,14.323l-1.49,6.452c-0.092,0.399,0.068,0.814,0.406,1.047C5.603,21.94,5.801,22,6,22 c0.193,0,0.387-0.056,0.555-0.168L12,18.202l5.445,3.63c0.348,0.232,0.805,0.223,1.145-0.024c0.338-0.247,0.487-0.68,0.372-1.082 l-1.829-6.4l4.536-4.082c0.297-0.268,0.406-0.686,0.278-1.064c-0.129-0.378-0.47-0.644-0.868-0.676L15.378,8.05l-2.467-5.461 C12.75,2.23,12.393,2,12,2s-0.75,0.23-0.911,0.589L8.622,8.05L2.921,8.503C2.529,8.534,2.192,8.791,2.06,9.16 c-0.134,0.369-0.038,0.782,0.242,1.056L6.516,14.323z"></path></svg>
					<span onclick="ShowProductReviews('<?php echo $wo['story']['product']['id'] ?>')" class="pointer"><?php echo $wo['story']['product']['reviews_count'] ?> <?php echo $wo['lang']['reviews']; ?></span>
				</div>
			<?php } ?>
		<?php
		echo '<div class="wow_post_prod_shead">';
		if (!empty($wo['story']['product']['location'])) {
			echo '<span> ' . $wo['story']['product']['location'] . '</span><span class="middot">·</span>';
		}
		echo '<span class="product-status"> ' . $status . '</span><span class="middot">·</span>';
		echo '<span> ' . $type . '</span>';
		echo '</div>';
		?>
		
		<div class="valign tag_post_prods_btns">
			<?php if ($wo['loggedin']) { ?>
				<?php if ($wo['story']['product']['user_id'] != $wo['user']['user_id']) { ?>
					<button class="save-product btn btn-mat<?php if($wo['story']['is_post_saved'] === true) { ?> active<?php } ?>" onclick="Wo_SavePost(<?php echo $wo['story']['id']; ?>);"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path></svg></button>
					<button class="contact btn btn-success btn-mat" onclick="Wo_OpenChatTab(<?php echo $wo['story']['product']['user_id']?>,0,<?php echo $wo['story']['product']['id']?>)"><?php echo $wo['lang']['contact_seller'] ?></button>
					<?php if ($wo['config']['store_system'] == 'on') { ?>
					<?php if (!empty($wo['story']['product']['units']) && $wo['story']['product']['units'] > 0) { ?>
						<button class="contact btn btn-main btn-mat" onclick="AddProductToCart(this,'<?php echo($wo['story']['product']['id']); ?>','add')"><?php echo($wo['lang']['buy_now']) ?></button>
					<?php }else{ ?>
					<?php } ?> 
					<?php } ?>
				<?php } ?>
			<?php } ?>
			<a class="btn btn-default btn-mat" href="<?php echo $wo['story']['url'];?>" data-ajax="?link1=post&id=<?php echo $wo['story']['id'];?>"><?php echo $wo['lang']['more_info']?></a>
		</div>
		
		<?php
		echo '<hr>';
		echo '<div class="wow_post_prod_infos"><p class="product-description product-description-'.$wo['story']['product']['id'].'">' . $wo['story']['product']['description'] . '</p></div>';
		$fields = Wo_GetCustomFields('product'); 
		if (!empty($fields)) {
			foreach ($fields as $key => $wo['field']) { 
				if (!empty($wo['story']['product']['fid_'.$wo['field']['id']])) {
					if ($wo['field']['type'] == 'selectbox') {
						$options = @explode(',', $wo['field']['options']);
						foreach ($options as $key => $value) {
							if (($key + 1) == $wo['story']['product']['fid_'.$wo['field']['id']]) {
								$wo['story']['product']['fid_'.$wo['field']['id']] = $value;
							}
						}
					}
					echo '<div class="wow_post_prod_infos"><p class="product-description">' . $wo['story']['product']['fid_'.$wo['field']['id']] . '</p></div>';
		        } 
		    } 
	    }
		echo '</div>';
		echo '</div>';
	} 
?>