<?php
declare(strict_types=1);

final class RACInstallerConfigWriter
{
    private ?string $temporaryFile = null;
    private ?string $backupFile = null;
    private ?string $originalContent = null;
    private bool $originalExisted = false;
    private bool $published = false;

    public function __construct(private readonly RACInstallerPaths $paths)
    {
    }

    public static function canWriteFreshConfig(string $path): bool
    {
        if (!file_exists($path)) {
            return is_dir(dirname($path)) && is_writable(dirname($path));
        }
        if (!is_file($path) || !is_readable($path) || !is_writable($path)) {
            return false;
        }
        $content = file_get_contents($path);
        if (!is_string($content)) {
            return false;
        }
        // A non-empty PHP configuration is always treated as an existing
        // installation. Older config files commonly contain an "e.g." URL
        // comment, so text heuristics can incorrectly authorize overwriting
        // real database credentials.
        return trim($content) === '';
    }

    public function prepare(array $database, array $site, string $purchaseCode, array $licenseCertificate = []): void
    {
        if (!self::canWriteFreshConfig($this->paths->configFile)) {
            throw new RACInstallerUserException('A populated config.php already exists. The installer will not overwrite it.');
        }

        $this->originalExisted = is_file($this->paths->configFile);
        $this->originalContent = $this->originalExisted ? file_get_contents($this->paths->configFile) : null;
        if ($this->originalExisted && !is_string($this->originalContent)) {
            throw new RACInstallerSystemException('Unable to preserve the config.php template for failure recovery.');
        }
        if ($this->originalExisted && is_string($this->originalContent)) {
            $this->backupFile = $this->writeTemporary($this->paths->logDir, 'rac-config-backup-', $this->originalContent);
        }
        $key = bin2hex(random_bytes(32));
        $certificatePayload = '';
        if ($licenseCertificate !== []) {
            $certificateJson = json_encode($licenseCertificate, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
            $certificatePayload = base64_encode($certificateJson);
        }
        $mobileLicensePublicKey = getenv('RAMZA_LICENSE_ED25519_PUBLIC_KEY');
        $mobileLicensePublicKey = is_string($mobileLicensePublicKey) ? trim($mobileLicensePublicKey) : '';
        $values = [
            'sql_db_host' => $database['host'],
            'sql_db_user' => $database['user'],
            'sql_db_pass' => $database['pass'],
            'sql_db_name' => $database['name'],
            'site_url' => $site['url'],
            'purchase_code' => $purchaseCode,
            'license_endpoint' => defined('RACSOCIAL_LICENSE_ENDPOINT') ? (string) constant('RACSOCIAL_LICENSE_ENDPOINT') : '',
            'license_certificate' => $certificatePayload,
            'siteEncryptKey' => $key,
            // Public verification material only. The Ed25519 private signing key stays on verify.expeazzy.com.
            'ramza_mobile_license_public_key' => $mobileLicensePublicKey,
            'table_prefix' => 'Wo_',
        ];
        $php = "<?php\n";
        $php .= "// Generated by the RACSocial installer. Keep this file outside public logs and backups.\n";
        foreach ($values as $name => $value) {
            $php .= '$' . $name . ' = ' . var_export((string) $value, true) . ";\n";
        }
        $php .= '$ramza_demo_mode = false;' . "\n";
        $php .= '$ramza_mobile_local_development = false;' . "\n";
        $php .= '$auto_redirect = true;' . "\n";

        try {
            token_get_all($php, TOKEN_PARSE);
        } catch (ParseError $error) {
            throw new RACInstallerSystemException('Generated PHP configuration failed syntax validation.', 0, $error);
        }

        $this->temporaryFile = $this->writeTemporary(dirname($this->paths->configFile), 'rac-config-', $php);
    }

    public function commit(): void
    {
        if ($this->temporaryFile === null || !is_file($this->temporaryFile)) {
            throw new RACInstallerSystemException('The prepared PHP configuration is unavailable.');
        }
        $this->replaceTemplate($this->temporaryFile, $this->paths->configFile);
        $this->temporaryFile = null;
        $this->published = true;
        @chmod($this->paths->configFile, 0640);
    }

    public function cleanup(): void
    {
        if ($this->temporaryFile !== null && is_file($this->temporaryFile)) {
            @unlink($this->temporaryFile);
        }
        $this->temporaryFile = null;
    }

    public function rollbackPublished(): void
    {
        if (!$this->published) {
            return;
        }
        if ($this->originalExisted && $this->backupFile !== null && is_file($this->backupFile)) {
            $backup = file_get_contents($this->backupFile);
            if (is_string($backup)) {
                file_put_contents($this->paths->configFile, $backup, LOCK_EX);
            }
        } else {
            @unlink($this->paths->configFile);
        }
        $this->published = false;
    }

    public function finalize(): void
    {
        if ($this->backupFile !== null && is_file($this->backupFile)) {
            @unlink($this->backupFile);
        }
        $this->backupFile = null;
        $this->originalContent = null;
    }

    private function writeTemporary(string $directory, string $prefix, string $content): string
    {
        $path = tempnam($directory, $prefix);
        $handle = $path === false ? false : fopen($path, 'wb');
        $written = $handle === false ? false : fwrite($handle, $content);
        if ($handle !== false) {
            fflush($handle);
            if (function_exists('fsync')) {
                fsync($handle);
            }
            fclose($handle);
        }
        if ($path === false || $written !== strlen($content)) {
            if (is_string($path)) {
                @unlink($path);
            }
            throw new RACInstallerSystemException('Unable to prepare the PHP configuration atomically.');
        }
        @chmod($path, 0600);
        return $path;
    }

    private function replaceTemplate(string $source, string $target): void
    {
        if (file_exists($target) && !self::canWriteFreshConfig($target)) {
            throw new RACInstallerUserException('config.php changed during installation and was not overwritten.');
        }
        if (file_exists($target) && !unlink($target)) {
            throw new RACInstallerSystemException('Unable to replace the config.php template.');
        }
        if (!rename($source, $target)) {
            throw new RACInstallerSystemException('Unable to publish config.php atomically.');
        }
    }
}
